### ISSUE TITLE
where to customized "jumpy.wordRegexp"

### ISSUE THREAD

**Issue by aQuaYi** [wmaurer/vscode-jumpy#10]
After pressing “F1” and typing “jumpy”， I can not find the place to customize jumpy.

**Comment by wmaurer** [comment]
File -> User Settings, and then add a new entry, e.g.:
```
    "jumpy.wordRegexp": "\\w{2,}"
```

I'll leave this issue open to remind me to add this to the README.

**Comment by aQuaYi** [comment]
Thank you very much.

**Comment by wmaurer** [comment]
The README has been updated.
