### ISSUE TITLE
Keybindings?

### ISSUE THREAD

**Issue by phcd30** [wmaurer/vscode-jumpy#2]
Would you have a sample Keybindings.json to show how the commands are hooked up in VS Code?

**Comment by krokofant** [comment]
I just setup the word jump like this:
```json
[
    {
        "key": "shift+enter",
        "command": "extension.jumpy-word",
        "when": "editorTextFocus"
    }
]
```

**Comment by wmaurer** [comment]
Thanks @krokofant, that's setup exactly with the keybinding that Atom uses.

@phcd30 you can also set up two-stroke keybindings, e.g.:
```
[
    {
        "key": "shift+enter w",
        "command": "extension.jumpy-word",
        "when": "editorTextFocus"
    },
    {
        "key": "shift+enter l",
        "command": "extension.jumpy-line",
        "when": "editorTextFocus"
    }
]
```
The VSCode documentation for setting up keybindings is:
https://code.visualstudio.com/docs/customization/keybindings
