### ISSUE TITLE
Please expand jumpy ranges to visibleRanges

### ISSUE THREAD

**Issue by toge** [wmaurer/vscode-jumpy#29]
Thank you for developing awesome plugin!

I want to use jumpy more widely.
How about expand jumpy ranges to texteditor.visibleRanges, as following.

`const plusMinusLines = vscode.window.activeTextEditor.visibleRanges[0].end.line - vscode.window.activeTextEditor.visibleRanges[0].start.line;
`

**Comment by primitiveType** [comment]
I have a portrait monitor that I code on and Jumpy doesn't really go far enough to cover the whole screen (it's about half). I would  love if it detected how many lines are on screen, but I would settle for being able to set how many lines it handles so I could just force it to do 100 lines or whatever.

**Comment by wenfangdu** [comment]
@toge @primitiveType Seems this extension is no longer being maintained, you can use [Jump](https://marketplace.visualstudio.com/items?itemName=wenfangdu.jump) instead, it supports this feature.

**Comment by toge** [comment]
Thank lots, @wenfangdu
I'm going to try yours.
