### ISSUE TITLE
Update available when it's not

### ISSUE THREAD

**Issue by krokofant** [wmaurer/vscode-jumpy#3]
I just updated from 0.0.1 to 0.0.2. VSCode says there is an update but updating does not install a version over 0.0.2.

I've tried uninstalling, reinstalling and restarting VSCode but no change.

Environment
Windows 10 x64
Visual Studio Code 1.5.3

**Comment by wmaurer** [comment]
I'm sorry, I believe that's a bug in VSCode. There is an update available, but it's only valid for VSCode 1.6+. You'd need to update VSCode to 1.6 to get the update.

**Comment by krokofant** [comment]
Thank you!

**Comment by wmaurer** [comment]
Ref Microsoft/vscode#13620
