### ISSUE TITLE
[Feature request] Exit search mode on ESC

### ISSUE THREAD

**Issue by krokofant** [wmaurer/vscode-jumpy#4]

**Comment by jcarter** [comment]
+1

**Comment by jcarter** [comment]
Not sure if you're already aware, @krokofant, but you can use the Enter/Return key to exit search mode.

**Comment by krokofant** [comment]
Thanks @jcarter, I'm aware but I feel the ESC is suitable to enter the editors normal mode. It's a common convention is it not?

**Comment by wmaurer** [comment]
I have just the minute released a new version with a command to exit `Jumpy Mode`. You can map this to ESC, by adding the following to your `keybindings.json`:
```
    {
        "key": "Escape",
        "command": "extension.jumpy-exit",
        "when": "editorTextFocus"
    }
```

This is also now documented in the README.

**Comment by krokofant** [comment]
Golden! I really appreciate your work.

**Comment by krokofant** [comment]
An update to this issue. The provided keybinding is blocking so it's blocking stuff intended for some other function as well.

An example is if you have an auto-complete box visible and want to close it. With the above mentioned keybinding it blocks the ESC signal to do what it should.

The *when* parameter should be specified more but I don't know how yet.

**Comment by krokofant** [comment]
@wmaurer 
To not make it block for me I used this:
```json
    {
        "key": "Escape",
        "command": "extension.jumpy-exit",
        "when": "editorTextFocus && !suggestWidgetVisible"
    }
```

I don't know if some cases are still blocked.

**Comment by krokofant** [comment]
Yes, it works perfectly!
