### ISSUE TITLE
confusion with vscode-jumpy-plus?

### ISSUE THREAD

**Issue by michaelaye** [wmaurer/vscode-jumpy#46]
Why is there another jumpy implementation with a "-plus" name, that still links to this repository but has a different user name(johnpyp vs @wmaurer ) ?
Would be good to clarify this on the extension page so that it is clear which one should be installed.

**Comment by wenfangdu** [comment]
@michaelaye I'm afraid this extension ​is no longer being maintained. I suggest existing users switch to [Jump](https://marketplace.visualstudio.com/items?itemName=wenfangdu.jump) instead.
