### ISSUE TITLE
[Feature request] Jumping across editors

### ISSUE THREAD

**Issue by krokofant** [wmaurer/vscode-jumpy#5]
Be able to open jumpy and have hints available in all editors for the same window.

**Comment by wmaurer** [comment]
It's a nice idea. I'll ask for a little bit of time for this one ... I'm going on holiday for a week ;-)

**Comment by krokofant** [comment]
@wmaurer Haha, I'm hammering you with issues. Sorry about that.

I'm not sure what the etiquette of issue filing is but my intention is to improve this project and not making demands. I'd figure if something annoys me enough I'll dig into it myself if I understand the extension system.

**Comment by wmaurer** [comment]
No probs ;-)

**Comment by krokofant** [comment]
I looked at the documentation for VSCode extension and didn't find a clear way of *identifying unique editors* and *declaring long-lived variables*. Do you have anything in mind for this? I imagine one would want to identify and save references to the "caller editor".

**Comment by wenfangdu** [comment]
@krokofant I'm afraid there's currently no reliable way to achieve jumping across all _visible_ editors in VSCode, but [Jump](https://marketplace.visualstudio.com/items?itemName=wenfangdu.jump) supports jumping through any _focused_ editor, you can give a try.
