### ISSUE TITLE
In Chinese, entering a punctuation mark will replace the previous character, and the punctuation will be entered twice

### ISSUE THREAD

**Issue by zdl958112850** [wmaurer/vscode-jumpy#52]
I like this plugin very much, but when inputting Chinese, there will be problems.
![1](https://raw.githubusercontent.com/zdl958112850/img/master/1.gif)

**Comment by zdl958112850** [comment]
I have tried, after closing the plug-in and restarting vscode, there is no such problem

**Comment by wenfangdu** [comment]
@zdl958112850 This extension is no longer maintained, I suggest existing users switch to [Jump](https://marketplace.visualstudio.com/items?itemName=wenfangdu.jump) instead.

As for your issue, I didn't reproduce it in Jump.

**Comment by zdl958112850** [comment]
Thank you very much, after using jump, the problem did not occur

**Comment by kp-bang** [comment]
系统：windows10
输入法：微软拼音输入法
操作顺序：shift + enter触发过jumpy，之后再输入全角逗号、句号等，或者拼音输入较快时，都会触发后面的字符覆盖前面的字符。
