### ISSUE TITLE
Allow customisation of decorations bg/fg decoration colours

### ISSUE THREAD

**Issue by wmaurer** [wmaurer/vscode-jumpy#6]
e.g background #00CC60, foreground #000000

**Comment by svenax** [comment]
Also customize font. The default is very small and hard to see.

**Comment by surfncode** [comment]
+1 to that. Too small for me too

**Comment by wmaurer** [comment]
@svenax, @surfncode thanks for the feedback. I'll look into what's possible with the vscode extension API.

**Comment by stormherz** [comment]
+1 for styling and font, on Mac OS consolas doesn't look very great and seems smaller =(

<img width="147" alt="screen shot 2016-12-22 at 20 24 13" src="https://cloud.githubusercontent.com/assets/235075/21427120/3e43d4be-c885-11e6-91bb-9356bddb4258.png">

**Comment by stormherz** [comment]
In fact, I'll even make a PR, if nobody minds. It will expose font family, font size, background-foreground colors

**Comment by wmaurer** [comment]
Sure, sounds good, I'd be happy for you to help out, thanks!

**Comment by pie6k** [comment]
I'm still having times new roman font.

Any ideas why that could be?

![image](https://user-images.githubusercontent.com/7311462/70814341-456a0800-1d99-11ea-9d9b-0607e3e34d24.png)

![image](https://user-images.githubusercontent.com/7311462/70814385-5c105f00-1d99-11ea-8b26-142b263af95f.png)

I've tried with various font families and it's the same all the time
