### ISSUE TITLE
Auto center editor window after jump

### ISSUE THREAD

**Issue by bohdan-meshcheriakov-artory** [wmaurer/vscode-jumpy#61]
It would be great feature to add. Now I'm using 'Center Editor Window' extension after each jump,
 it would be nice to have a setting which automatically doing it.
 Ready to help with contribution on this one.

**Comment by wenfangdu** [comment]
@bohdan-meshcheriakov-artory [Jump](https://marketplace.visualstudio.com/items?itemName=wenfangdu.jump) respects `editor.cursorSurroundingLines`, you can give it a try.

**Comment by bohdan-meshcheriakov-artory** [comment]
Hey, thanks. Set it to 100, it solved the problem. Issue solved)
