### ISSUE TITLE
[Bug] Decorations visible in non-jumpy mode

### ISSUE THREAD

**Issue by krokofant** [wmaurer/vscode-jumpy#8]
Jumpy: 0.2.1
VSCode: 1.6.0
# Replicate
1. Create two editors in single window
2. Activate Jumpy
3. Switch to the other editor
4. Press `enter` or any decoration shortcut
5. The decorations are showing outside of Jumpy mode

**Comment by wmaurer** [comment]
Thanks I'll look into this along with the jumping across editors feature request.
